# Generated by Django 5.0.6 on 2024-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_departments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='password',
            field=models.CharField(default='hvrqnzat', max_length=150),
        ),
    ]
