# Generated by Django 5.0.6 on 2024-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_departments_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='password',
            field=models.CharField(default='pwshrfgc', max_length=150),
        ),
    ]
