# Generated by Django 5.0.6 on 2024-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_departments_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
