# Generated by Django 5.0.6 on 2024-06-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_departments_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='title',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
