# Generated by Django 5.0.6 on 2024-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_departments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
