# Generated by Django 5.0.6 on 2024-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_remove_user_access_user_access_lvl_delete_accesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_kadr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
